DDMAL/UMIL

- README.md
In order to complete #6, we'll make `develop` the default branch...but first, we merge `main` into `develop` so that we have all the latest code in `develop`
> Merge `main` to `develop` to prepare for new branch structure

- web-app/django/VIM/apps/instruments/templates/instrument_list.html
- web-app/django/VIM/apps/instruments/views/instrument_list.py
- web-app/django/VIM/urls.py
> Create basic instrument gallery view

- .github/workflows/python_format.yml
Adds a GitHub action targeting pull requests that executes a `black` formatting check to python code.
> Add python formatting action

- web-app/Dockerfile
- web-app/django/VIM/apps/instruments/templates/instruments/index.html
- web-app/django/VIM/apps/main/templates/main/about.html
- web-app/django/VIM/apps/main/templates/main/index.html
- web-app/django/VIM/locale/en/LC_MESSAGES/django.po
- web-app/django/VIM/locale/fr/LC_MESSAGES/django.po
- web-app/django/VIM/settings.py
- web-app/django/VIM/templates/404.html
- web-app/django/VIM/templates/base.html
- web-app/django/VIM/urls.py
- Translated page content into French (by ChatGPT)
- Added language switch button function
Next step:
Check if google translate API can automatically translate page content while leave some content untouched for instrument names
> Django internationalization with French

- web-app/django/VIM/apps/instruments/templates/instruments/includes/listView.html
- web-app/django/VIM/apps/instruments/templates/instruments/includes/masonryView.html
- web-app/django/VIM/apps/instruments/templates/instruments/includes/stdView.html
Sry, forgot to push this change!
> Language switch for instrument name

- web-app/django/VIM/apps/instruments/static/instruments/js/pagination.js
- web-app/django/VIM/apps/instruments/templates/instruments/includes/pageSetting.html
- web-app/django/VIM/apps/instruments/templates/instruments/index.html
- web-app/django/VIM/apps/instruments/views/instrument_list.py
* Create a modal window for pagination setting
* Save pagination settings in localStorage
* Pagination setting input validation (avoid invalid values)
> User pagination settings

- docker-compose.yml
- solr/Dockerfile
- solr/cores/conf/schema.xml
- solr/cores/conf/solrconfig.xml
- solr/cores/core.properties
- web-app/django/VIM/apps/instruments/management/commands/index_data.py
- web-app/django/VIM/apps/instruments/views/instrument_list.py
Provides a back-end solution for faceting by the first two levels of the Hornbostel-Sachs Classification scheme. Provides a dictionary of facet counts in the InstrumentListView.
> Provide backend for HBS faceting

- web-app/django/VIM/apps/instruments/management/commands/index_data.py
- web-app/django/VIM/apps/instruments/static/instruments/css/index.css
- web-app/django/VIM/apps/instruments/templates/instruments/index.html
- web-app/django/VIM/apps/instruments/views/instrument_list.py
> Add front-end for Hornbostel-Sachs faceting

- .github/workflows/cd_stage.yml
Fix #71
1. Deploy to stage server with Github Action
2. Triggered by pushes to `develop` branch
> Fix #71, Deploy to stage server with Github Action

- web-app/django/VIM/static/css/app.css
> fix: make google translate selector fixed width

- web-app/django/VIM/apps/instruments/management/commands/download_imgs.py
> fix: apply flexible compression ratio

- web-app/django/VIM/apps/instruments/templates/instruments/index.html
- web-app/django/VIM/apps/main/templates/main/index.html
> fix: replace lowercases with uppercases in urls

- .djlintrc
> fix: replace list with string in .djlintrc

- web-app/django/VIM/apps/main/templates/registration/login.html
- web-app/django/VIM/templates/base.html
- Temporarily remove "search..." on the top right.
- Temporarily remove "forget your password" button (as we can't sent emails).
- Move "register" button.
Resolves: #176 
Resolves: #180
> fix: remove features which don't work

- .github/workflows/frontend_format.yml
> fix: edit frontend_format.yml

- README.md
- Resolves https://github.com/DDMAL/VIM/issues/197
> Adding local development instruction to download thumbnail images

- web-app/django/VIM/static/css/app.css
> style: scroll dropdown independently from whole page

- web-app/django/VIM/static/css/main/login.css
- web-app/django/VIM/templates/main/registration/changePassword.html
- web-app/django/VIM/templates/main/registration/login.html
- web-app/django/VIM/templates/main/registration/register.html
- web-app/django/VIM/templates/main/registration/registration_base.html
- web-app/django/VIM/templates/main/registration/resetPassword.html
- web-app/django/VIM/templates/main/registration/resetPasswordComplete.html
- web-app/django/VIM/templates/main/registration/resetPasswordConfirm.html
- web-app/django/VIM/templates/main/registration/resetPasswordDone.html
- Created `registration_base.html` to avoid code duplications
- Removed unused code
refs: #181
preview:
> style: fix account container cuts off navbar and foot

- web-app/django/VIM/apps/instruments/views/instrument_list.py
- web-app/django/VIM/static/css/app.css
- web-app/django/VIM/static/js/LanguageList.js
- web-app/django/VIM/templates/instruments/index.html
- Reorder the language list according to en_label;
- Adjust the dropdown box style;
- Support language search functionality;
Resolves: #210
> fix: reorder language list

- web-app/django/VIM/templates/instruments/includes/listView.html
- web-app/django/VIM/templates/instruments/includes/stdView.html
> fix: update image placeholder path

- .github/workflows/frontend_format.yml
- .pre-commit-config.yaml
- .prettierignore
- web-app/frontend/package-lock.json
- web-app/frontend/package.json
- web-app/frontend/src/GoogleTranslate.ts
- web-app/frontend/src/LanguageList.ts
- web-app/frontend/src/LanguageTooltip.ts
- web-app/frontend/src/instruments/PaginationTools.ts
- web-app/frontend/vite.config.js
- Added prettier dependency
- Ensured pre-commit hook, CI format check, and local all use the same version of prettier
refs: #225
> Add prettier dependency

- web-app/django/VIM/templates/main/index.html
> fix: edit button text

- web-app/frontend/package.json
- This is to fix compile error in production mode
refs: #251
> build(temp): make sass and vite dependency (not dev)

- web-app/django/VIM/apps/instruments/management/commands/index_data.py
- web-app/django/VIM/apps/instruments/views/instrument_list.py
- web-app/django/VIM/templates/instruments/index.html
- Only store English hbs labels, use Google Translate for other languages;
- Enable Google Translate of hbs facet search.
Resolves: #265
Resolves: #230
> fix: fix & refactor index data

- README.md
Resolves: #269 
Resolves: #261
> docs: clarify usage of `index_data` command in README

- web-app/django/VIM/templates/base.html
> fix: remove UMIL icon

- web-app/django/VIM/templates/instruments/detail.html
> fix: disable translate of label

- web-app/django/VIM/templates/base.html
> feat: add Google Analytics tag

- web-app/django/VIM/apps/instruments/management/commands/import_instruments.py
- web-app/django/VIM/templates/instruments/detail.html
- web-app/frontend/src/instruments/CollapseTable.ts
- web-app/frontend/vite.config.js
> feat: import labels in more languages

- web-app/django/VIM/templates/instruments/includes/paginationOptions.html
- web-app/django/VIM/templates/instruments/index.html
> style: add pagination at top 

- web-app/django/VIM/templates/base.html
> fix: remove Google Tag installation & add GTM

- .github/workflows/cd_prod.yml
- I created:
- `main` branch
- PROXY_HOST_PROD secret
- HOST_PROD secret
- `cd_prod.yml` file
- What this action does: On push to `main` branch:
- Change directory to `/virtual_instrument_museum`
- Stop the containers
- Fetch new updates from remote `origin` and log current branches
- Checkout to `main` branch and pull new changes 
- Build Docker images, without cache
- Compose up all services, including the new changes
> Production CD Github Action

- .github/workflows/cd_stage.yml
> Update Staging CD to build Docker with no cache

- web-app/django/VIM/templates/instruments/index.html
> fix: prevent bottom imgs from being covered

- web-app/django/VIM/templates/instruments/detail.html
- Moved add-name button to the same row as toggle button
- Made table scrollable and height adjustable
refs: #387
preview:
> fix: improve instrument table UI
