docker-compose.yml
nginx/vim.conf.template
web-app/django-startup.sh
web-app/django/VIM/settings.py

Closes #48.
Static files are collected into a docker volume that is shared between the `app` and `nginx` containers. Nginx then serves these static files. NOTE: this means all static files must be placed in static folders recognized by django (configurable in `settings.py`) and all references to static files (eg. in templates) should use the `/static/` url.

Serve static files with nginx

---

.env.sample
README.md
docker-compose.yml
web-app/django/VIM/settings.py

Fixes #62.
Also adjusts the CSRF Trusted Origins setting.

Deployment fixes

---

web-app/django/VIM/apps/instruments/static/instruments/css/index.css
web-app/django/VIM/apps/instruments/static/instruments/css/pagination.css
web-app/django/VIM/apps/instruments/static/instruments/js/DisplaySettings.js
web-app/django/VIM/apps/instruments/templates/instruments/index.html
web-app/django/VIM/apps/instruments/views/instrument_list.py

Fix all issues in #87 
* Highlight the chosen facet in sidebar; Show the chosen facet name in Instrument View;
* Unhighlight the current page number on the "Page X of Y" area;
* Have page layout icons (upper right corner of the instrument list) side-by-side and highlight the one that is selected;
* Adjust margin bottom of sidebar;

Adjust instrument list view UI

---

web-app/django/VIM/apps/instruments/static/instruments/js/DisplaySettings.js
web-app/django/VIM/apps/instruments/templates/instruments/index.html
web-app/django/VIM/apps/main/static/main/css/index.css
web-app/django/VIM/apps/main/templates/registration/change_password.html
web-app/django/VIM/apps/main/templates/registration/login.html
web-app/django/VIM/apps/main/templates/registration/reset_password.html
web-app/django/VIM/apps/main/templates/registration/reset_password_complete.html
web-app/django/VIM/apps/main/templates/registration/reset_password_confirm.html
web-app/django/VIM/apps/main/templates/registration/reset_password_email.html
web-app/django/VIM/apps/main/templates/registration/reset_password_sent.html
web-app/django/VIM/apps/main/urls.py
web-app/django/VIM/settings.py
web-app/django/VIM/static/css/app.css
web-app/django/VIM/templates/base.html

Fix issues #92 #93 #95 #96.
For #94, The configuration of sending emails has not been completed yet, the UI part has been completed.

Fix some UI issues

---

README.md
web-app/django/VIM/apps/main/templates/main/about.html
web-app/django/VIM/apps/main/templates/main/index.html
web-app/django/VIM/templates/base.html
web-app/django/VIM/urls.py

Affecting header and "about" section only, changed VIM to UMIL and Virtual Instrument Museum to Universal Musical Instrument Lexicon.

Changed VIM and Virtual Instrument Museum to UMIL

---

web-app/django/VIM/apps/instruments/static/instruments/js/DisplaySettings.js
web-app/django/VIM/apps/instruments/templates/instruments/includes/paginationOptions.html
web-app/django/VIM/apps/instruments/templates/instruments/index.html
web-app/django/VIM/static/js/GoogleTranslate.js
web-app/django/VIM/static/js/LanguageTooltip.js
web-app/django/VIM/templates/base.html

**Fix: Improve accessibility with `@title` attribute and modularize pagination options**
- Set `@title` attribute instead of tooltip for better accessibility in pagination settings.
- Modularized HTML for pagination options to enhance maintainability.
Resolves: #112
**Fix: Enhance webpage language tooltip functionality**
- Converted webpage language badge to use tooltips.
- Removed deprecated code related to language button badge.
- Moved tooltip scripts to `LanguageTooltip.js`.
Resolves: #111

Enhance Accessibility and Tooltip Functionality

---

.djlintrc
.editorconfig
.github/workflows/frontend_format.yml
prettierrc.yml
web-app/django/VIM/apps/instruments/static/instruments/css/index.css
web-app/django/VIM/apps/instruments/static/instruments/css/pagination.css
web-app/django/VIM/apps/instruments/static/instruments/js/DisplaySettings.js
web-app/django/VIM/apps/instruments/static/instruments/js/PaginationTools.js
web-app/django/VIM/apps/instruments/templates/instruments/includes/listView.html
web-app/django/VIM/apps/instruments/templates/instruments/includes/masonryView.html
web-app/django/VIM/apps/instruments/templates/instruments/includes/paginationOptions.html
web-app/django/VIM/apps/instruments/templates/instruments/includes/stdView.html
web-app/django/VIM/apps/instruments/templates/instruments/index.html
web-app/django/VIM/apps/main/static/main/css/about.css
web-app/django/VIM/apps/main/static/main/css/index.css
web-app/django/VIM/apps/main/static/main/css/login.css
web-app/django/VIM/apps/main/templates/main/about.html
web-app/django/VIM/apps/main/templates/main/index.html
web-app/django/VIM/apps/main/templates/registration/change_password.html
web-app/django/VIM/apps/main/templates/registration/login.html
web-app/django/VIM/apps/main/templates/registration/register.html
web-app/django/VIM/apps/main/templates/registration/reset_password.html
web-app/django/VIM/apps/main/templates/registration/reset_password_complete.html
web-app/django/VIM/apps/main/templates/registration/reset_password_confirm.html
web-app/django/VIM/apps/main/templates/registration/reset_password_email.html
web-app/django/VIM/apps/main/templates/registration/reset_password_sent.html
web-app/django/VIM/static/css/app.css
web-app/django/VIM/static/js/GoogleTranslate.js
web-app/django/VIM/templates/404.html
web-app/django/VIM/templates/base.html

- Set up djlint for HTML, prettier for JS and CSS.
- Reformatted front end code to adhere to established formatting standards.
- Added CI workflow for front end format check.
Closes #113

Implement Front End Code Formatting

---

.pre-commit-config.yaml

- Use black for python, djlint for html, prettier for css and js
Resolves: #117

ci: init pre-commit hook for code reformatting

---

web-app/django/VIM/apps/instruments/static/instruments/css/detail.css
web-app/django/VIM/apps/instruments/static/instruments/css/index.css
web-app/django/VIM/apps/instruments/static/instruments/js/InstrumentDetail.js
web-app/django/VIM/apps/instruments/templates/instruments/detail.html
web-app/django/VIM/apps/instruments/templates/instruments/includes/masonryView.html
web-app/django/VIM/apps/instruments/templates/instruments/includes/stdView.html
web-app/django/VIM/apps/instruments/views/instrument_detail.py
web-app/django/VIM/urls.py

1. **Added CSS for instrument detail view**:
- Created `detail.css` to place most of styles of instrument detail page;
- Updated `index.css` for instrument module global style;
2. **Added JavaScript for instrument detail interactions**:
- Created `InstrumentDetail.js`: initialize `edit`, `cancel` and `publish` button listeners;
3. **Created and updated HTML templates**:
- Created `detail.html`: Initialize instrument detail html #32 ;
- Updated `masonryView.html` and `stdView.html`: when clicking on an image;
4. **Added view for instrument detail**:
- Created `instrument_detail.py`: initialize the `InstrumentDetail` class as a `DetailView` #33 ;
- Improved query efficiency by utilizing `context["instrument"]` instead of `get_object`.
- Prepared for future language support by retrieving …

feat: initialize instrument detail page

---

poetry.lock
pyproject.toml
web-app/django/VIM/apps/instruments/templates/instruments/includes/listView.html
web-app/django/VIM/apps/instruments/templates/instruments/includes/masonryView.html
web-app/django/VIM/apps/instruments/templates/instruments/includes/stdView.html
web-app/django/VIM/apps/instruments/views/instrument_list.py
web-app/install-packages.sh

This PR refactors the `InstrumentList` view and associated templates to reduce the number of database queries. See profile:
We now select and prefetch related objects, using a custom related objects manager to filter instrument names on the backend, rather than during template rendering (the cause of a great many of the duplicate queries).
The PR also adds some additional python development dependencies to the `pyproject.toml` file:
- `djlint` was configured for html template formatting but had not been added as a dependency
- stubs for the `django` and `requests` packages are added for type checking
Closes #141

Reduce duplicate queries on instrument list view

---

web-app/django/VIM/templates/base.html

Parameters to the `static` template tag should be relative paths to avoid a `SuspiciousFileOperation` exception. See comments of #143 for details.

Remove opening slash from script src paths in `base.html`

---

web-app/django/VIM/settings.py

- Frontend files are built to `web-app/frontend/dist/` in prod mode only. This should resolve the path doesn't exist error in development mode.
refs: #224

build: set `STATICFILES_DIR` for prod mode only

---

README.md

- After changes in #208, need to navigate to `vim-app/` to access `manage.py`
refs: #243

docs: add directory navigation

---

web-app/django/VIM/templates/base.html
web-app/django/VIM/templates/instruments/index.html
web-app/django/VIM/templates/main/index.html
web-app/django/VIM/templates/main/registration/changePassword.html
web-app/django/VIM/templates/main/registration/login.html
web-app/django/VIM/templates/main/registration/register.html
web-app/django/VIM/templates/main/registration/registration_base.html
web-app/django/VIM/templates/main/registration/resetPassword.html
web-app/django/VIM/templates/main/registration/resetPasswordComplete.html
web-app/django/VIM/templates/main/registration/resetPasswordDone.html
web-app/frontend/assets/css/main/index.css
web-app/frontend/assets/css/main/login.css

Implement responsive design

---

poetry.lock
pyproject.toml
solr/cores/conf/schema.xml
web-app/django/VIM/apps/instruments/management/commands/index_data.py
web-app/django/VIM/apps/instruments/views/instrument_detail.py
web-app/django/VIM/apps/instruments/views/instrument_list.py
web-app/django/VIM/settings.py
web-app/django/VIM/templates/base.html
web-app/django/VIM/templates/instruments/index.html

Implement the search bar using Django ORM search.
Resolves: #186

feat: search bar

---

README.md
web-app/django/VIM/apps/instruments/management/commands/download_imgs.py
web-app/django/VIM/apps/instruments/management/commands/import_instruments.py
web-app/django/startup_data/umil_instruments_15July_2025.csv

- delete invalid entries (don't have a QID)
- remove redundant entries
- fix broken special characters
- will log in to staging/production server after merging to run the data loading commands.
resolves: #183

fix: cleanup & update instrument data

---

web-app/django/VIM/apps/main/views.py
web-app/django/VIM/templates/main/index.html
web-app/frontend/assets/scss/_bootstrap-overrides.scss
web-app/frontend/src/StatsAnimation.ts
web-app/frontend/vite.config.js

refs: #185
Although the issue specifies the About page, I think these numbers look better on the Home page, as it aligns with the convention of a hero section. This is the initial PR to add only the stats numbers; I will include the remaining charts in a separate PR.
Preview:

feat: add stats number to home page

---

web-app/Dockerfile

- This is needed otherwise docker will try to run `npm run dev` in `/virtual-instrument-museum` instead of `frontend/`
refs: #311

build: fix frontend path error

---

web-app/django/VIM/apps/instruments/views/instrument_list.py

- Added `SolrPaginator` to handle pagination of Solr search results with total count.
- Added private methods to support Solr search and pagination.
- Updated `paginate_queryset` method to integrate Solr search handling.
- Refactored search query handling to return a signal maker for Solr search.
- This change is adaptable for future integration with HBS filtering.
refs: https://github.com/DDMAL/UMIL/issues/330

feat: custom pagination for Solr search result 

---

.github/workflows/cd_prod.yml

On production server, the app is in `virtual-instrument-museum` instead of `virtual_instrument_museum` (hyphen instead of underscore)

Typo fix: change folder name for production server
